name: hello-world
on: push
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
     - name: check out repository code
       uses: actions/checkout@v4
     - name: displays content of the file
       run: echo "$(cat hello_world.txt)"
